### ISSUE TITLE
Client Script Files

### ISSUE THREAD

**Issue by Glyphix311** [ServiceNow/devtraining-needit-sandiego#132]
Hey,

     I am new to ServiceNow and I am going through the courses on the Developers site. I finished the module for creating the NeedIt application and now I am on to the Client Scripts. I had no issues creating the app. However on the Client Script module I cannot seem to find the script  (example Onload) files within the repository to test them. I did everything I could think of to correct it and still no luck. 

If there is any assistance you can help me that would be greatly appreciated.

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
> 
I also enountered similar situation. I created a new client script (onload etc...) inorder to be able to follow along with the testing.

**Comment by Glyphix311** [comment]
> > 
> 
> I also enountered similar situation. I created a new client script (onload etc...) inorder to be able to follow allong with the testing.

I appreciate the response, that was my next course of action. I didn't want to move on until I explored the issue further. 

Thank you.

**Comment by bsweets** [comment]
Did you both create the branch from the LoadForClientScriptsModule tag per the instructions in the module? https://developer.servicenow.com/dev.do#!/learn/courses/sandiego/app_store_learnv2_scripting_sandiego_scripting_in_servicenow/app_store_learnv2_scripting_sandiego_client_side_scripting/CSS_Lab_CreateBranch_sandiego

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
> Did you both create the branch from the LoadForClientScriptsModule tag per the instructions in the module? https://developer.servicenow.com/dev.do#!/learn/courses/sandiego/app_store_learnv2_scripting_sandiego_scripting_in_servicenow/app_store_learnv2_scripting_sandiego_client_side_scripting/CSS_Lab_CreateBranch_sandiego

I do not think that exists in the github repo... if it does, please can you explain how to approach that.
Thank you.

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
![Screenshot 2022-08-19 at 18 52 53](https://user-images.githubusercontent.com/81686044/185668953-9e9c53ec-815b-4ea8-9d5c-4cc9f31c2b46.png)
> https://developer.servicenow.com/dev.do#!/learn/courses/sandiego/app_store_learnv2_scripting_sandiego_scripting_in_servicenow/app_store_learnv2_scripting_sandiego_client_side_scripting/CSS_Lab_CreateBranch_sandiego

When I click on create branch, only "Branch Name:" is visible.
I do not see "Create from Tag:" or do I have to do something or that to show up?
![Screenshot 2022-08-19 at 18 39 09](https://user-images.githubusercontent.com/81686044/185667796-78fe6330-3e94-4947-91d2-8f7ce48be102.png)

**Comment by bsweets** [comment]
@Ifeanyi-Kingsley-Nwabor, Interesting... I just took a look at your NeedIt repository fork, and you are missing all the tags for some reason. This would be why you cannot create a branch from a tag and why you do not see the box to select the tag. 

![image](https://user-images.githubusercontent.com/36206043/185678117-9854393a-24c3-410e-a287-568b21051535.png)

@Glyphix311, your fork has the same issue. I have not seen this happen before, so it is especially weird for it to happen twice.

You can see in the original repository that you fork, there are many tags:

![image](https://user-images.githubusercontent.com/36206043/185678276-f131fa55-ca32-456f-83c7-db6d9bcda9f9.png)

I don't think either of you have gotten far. I think your best option is to [delete your fork of the repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository), and then follow the steps in the fork exercise to recreate your copy of the repository we provide. 

I'm sorry for the issues here. If your fork does not have the tags again, let me know.

**Comment by Glyphix311** [comment]
@bsweets So I have actually spent the last two days trying to figure this out and I have had no luck. I went into extensive work trying to figure this out. Now I am just curious. To explain what I have tried, I deleted everything and started over, redid the fork, the credentials, everything. I created a new PDI and I also tried the Tokyo repo since I saw the files were in there. That also did not work. I made another GitHub account, did the entire process in that new account and it also did not work. I had someone else use the Tokyo repo to their PDI and it loaded just fine. The files are not transferring in the repo for me. For the life of me I cannot figure it out.

**Comment by Glyphix311** [comment]
![image](https://user-images.githubusercontent.com/111229119/185682356-1e433acd-0e14-4ab3-9305-d7ccc01cc849.png)

This is my repo for Tokyo currently and also no tags.

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
> @Ifeanyi-Kingsley-Nwabor, Interesting... I just took a look at your NeedIt repository fork, and you are missing all the tags for some reason. This would be why you cannot create a branch from a tag and why you do not see the box to select the tag.
> 
> ![image](https://user-images.githubusercontent.com/36206043/185678117-9854393a-24c3-410e-a287-568b21051535.png)
> 
> @Glyphix311, your fork has the same issue. I have not seen this happen before, so it is especially weird for it to happen twice.
> 
> You can see in the original repository that you fork, there are many tags:
> 
> ![image](https://user-images.githubusercontent.com/36206043/185678276-f131fa55-ca32-456f-83c7-db6d9bcda9f9.png)
> 
> I don't think either of you have gotten far. I think your best option is to [delete your fork of the repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/deleting-a-repository), and then follow the steps in the fork exercise to recreate your copy of the repository we provide.
> 
> I'm sorry for the issues here. If your fork does not have the tags again, let me know.

I have deleted the fork and started over more than 3 times, still no option to load the tags. when I click the create branch, only the Branch Name field is shown and nothing with regards to tags. 
Just saying, something is definitely wrong somewhere, either from me but i dont know how or from the service now updated versions etc.... I have been in this for almost 2 weeks, deleting and starting from scratch just to follow allong. I also found a couple of inconsistensies which I believe ServiceNow might want to correct for the learning purposes.

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
> ![image](https://user-images.githubusercontent.com/111229119/185682356-1e433acd-0e14-4ab3-9305-d7ccc01cc849.png)
> 
> This is my repo for Tokyo currently and also no tags.

If this won't be a problem, I was hoping we could do some knowledge sharing if you have the time considering we might actually be on same boat. I mean, I believe I could learn something valuable from you.

**Comment by bsweets** [comment]
I tried to replicate what you are both seeing and noticed GitHub has added an option recently that I have not seen. There is now an option to only copy the main branch when you fork. Doing so would cause you to not get any of the tags we provide you. Be sure to deselect the **Copy the main branch only** option when you create your fork.

I've highlighted it with the default value here. Be sure to deselect it.

![image](https://user-images.githubusercontent.com/36206043/185687238-8e232fde-8fea-4f36-83e3-6775cea979d0.png)

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
> I tried to replicate what you are both seeing and noticed GitHub has added an option recently that I have not seen. There is now an option to only copy the main branch when you fork. Doing so would cause you to not get any of the tags we provide you. Be sure to deselect the **Copy the main branch only** option when you create your fork.
> 
> I've highlighted it with the default value here. Be sure to deselect it.
> 
> ![image](https://user-images.githubusercontent.com/36206043/185687238-8e232fde-8fea-4f36-83e3-6775cea979d0.png)

Ahhh... ok.
Thank you very much. Am on it but do I have to delete tha NeedIt application and redo the excercises from the begining?

**Comment by bsweets** [comment]
I was able to replicate the issue when I left that option selected. It looks like GitHub added this around July 27, and I didn't know people were having issues until I saw your posts. Thank you both for bearing with me here. I am very sorry for the frustration this has caused you.

**Comment by Glyphix311** [comment]
> I was able to replicate the issue when I left that option selected. It looks like GitHub added this around July 27, and I didn't know people were having issues until I saw your posts. Thank you both for bearing with me here. I am very sorry for the frustration this has caused you.

I appreciate you taking the time to help us figure this out. Being as this is a recent change to GitHub none of the researching I did resulted in a solution. Since making the change it has worked for me. 

Thank you for helping find and fix our issues, I am back on my way to learning!

**Comment by bsweets** [comment]
Excellent! Now I only have about 100 learning modules to update with this change GitHub made... ugh... ;P

**Comment by bsweets** [comment]
> > ![image](https://user-images.githubusercontent.com/111229119/185682356-1e433acd-0e14-4ab3-9305-d7ccc01cc849.png)
> > This is my repo for Tokyo currently and also no tags.
> 
> If this won't be a problem, I was hoping we could do some knowledge sharing if you have the time considering we might actually be on same boat. I mean, I believe I could learn something valuable from you.

@Ifeanyi-Kingsley-Nwabor, I just found your developer record on the Developer Site and will reach out to you directly. It sounds like you might have some other questions. Watch for an email from me.

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
> ![image](https://user-images.githubusercontent.com/111229119/185682356-1e433acd-0e14-4ab3-9305-d7ccc01cc849.png)
> 
> This is my repo for Tokyo currently and also no tags.

If this won't be a problem, I was hoping we could do some knowledge sharing if you have the time considering we might actually be on same boat. I mean, I believe I could learn something valuable from you.

**Comment by Glyphix311** [comment]
> Excellent! Now I only have about 100 learning modules to update with this change GitHub made... ugh... ;P

Sorry for giving you more work! I feel like I should of caught that little button sooner, but when trying to learn things step by step I tried to stick what was provided. My only trouble shooting was restarting each time. I do apologize but it is greatly appreciated it!

**Comment by bsweets** [comment]
YOU didn't give me more work! You simply reported having an issue. I'm sorry you spent a couple of days trying to figure out what was happening when it only took me a couple of minutes to find the issue by stepping through the process. If you hadn't reported the issue, others would have run into the problem, too. This is a pretty big change for GitHub to push out with the option enabled by default. Frankly, it is GitHub that gave me more work here. Unless you work for GitHub and want to take the blame... ;P

**Comment by Glyphix311** [comment]
> YOU didn't give me more work! You simply reported having an issue. I'm sorry you spent a couple of days trying to figure out what was happening when it only took me a couple of minutes to find the issue by stepping through the process. If you hadn't reported the issue, others would have run into the problem, too. This is a pretty big change for GitHub to push out with the option enabled by default. Frankly, it is GitHub that gave me more work here. Unless you work for GitHub and want to take the blame... ;P

Haha, I don't want to get in trouble by saying this, hopefully GitHub won't get mad but I am fine with them taking the blame! It is amazing how one check box can send you through two days of trouble shooting. I did learn a lot in the process, believe it or not. I don't consider it time wasted. I am sure this won't be my first run in with a minor issue that takes me longer then it should of to resolve!

If you want to hire someone to make those fixes, i'll do it!

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
> I was able to replicate the issue when I left that option selected. It looks like GitHub added this around July 27, and I didn't know people were having issues until I saw your posts. Thank you both for bearing with me here. I am very sorry for the frustration this has caused you.

It was a great opportunity for learning. Thank you for taking the time to assist us with this.

**Comment by bsweets** [comment]
Thank you both again. You shouldn't need to deal with it again, because you both have working forks of the repository, but I've updated the forking instructions for all our learning content and am just finishing up the imports for the updated content. My manager said he forked earlier in the week, so hopefully we caught this one early and others don't really hit this issue. Thank you again.

**Comment by Ifeanyi-Kingsley-Nwabor** [comment]
> Thank you both again. You shouldn't need to deal with it again, because you both have working forks of the repository, but I've updated the forking instructions for all our learning content and am just finishing up the imports for the updated content. My manager said he forked earlier in the week, so hopefully we caught this one early and others don't really hit this issue. Thank you again.

Thank you for your prompt response and assistance.
